### ISSUE TITLE
Correct errors in Packstack install instructions

### ISSUE THREAD

**Issue by richbrowne** [F5Networks/f5-openstack-docs#173]
There are a few issues with the install instructions on the Packstack deploy page.

The yum update command needs to be, yum update -y and not yum install update
The yum commands to install openstack-rdo and packstack.

Also the openstack-rdo URL points to Kilo.

**Comment by richbrowne** [comment]
I have the fixes, but would like to know which branch to push the fixes to.  Should I put this in mitaka and master?

**Comment by jputrino** [comment]
Is this the same as #174? See comment there. You can push the changes to Kilo and then merge up to the other branches. Kilo is the only version I know is in parity with the RDO docs. 
As I mentioned in the issue opened by @mattgreene, these OpenStack deployment and configuration docs are going to be deprecated in favor of providing links to our partners' documentation. See #172.
