### ISSUE TITLE
Correct errors on the 'deploy getting started page'

### ISSUE THREAD

**Issue by mattgreene** [F5Networks/f5-openstack-docs#174]
#### Agent Version
N/A

#### Operating System
N/A

#### OpenStack Release
All

#### Description
The following page has multiple errors:
http://f5-openstack-docs.readthedocs.io/en/latest/guides/map_os-deploy-getting-started.html#install-software-repositories
Section = Install Software Repositories
Step 2 needs to reference the correct release.  All versions currently refer to kilo.
Steps 2 and 3 need to specify the yum command between "sudo" and "install".

#### Deployment
N/A

**Comment by jputrino** [comment]
This document is being deprecated. Instead, we will provide links to our partners' documentation for installing and configuring OpenStack.
