### ISSUE TITLE
Remove 12.0 support from releases_and_versioning.rst

### ISSUE THREAD

**Issue by pjbreaux** [F5Networks/f5-openstack-docs#203]
#### OpenStack Release
liberty going forward

#### Description
We should remove BIG-IP 12.0 from the releases_and_versioning.rst page. Newton will already have this change, but we need to update the matrix for liberty and mitaka.

**Comment by jputrino** [comment]
Closing -- we will not have openstack-release-specific branches for this repo after moving to clouddocs. The change is already in master.
