### ISSUE TITLE
location of f5.tgz is incorrect

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/f5-openstack-docs#240]
// Title: Provide a short but descriptive summary of the issue.
On a couple pages, f5.tgz is referenced in code as "|f5_lbaasv2_driver_shim_url|"

// **Do not include requests for development or report issues with code or products here.** 
On this page:
http://clouddocs.f5.com/cloud/openstack/v1/lbaas/quick-reference.html
It manifests itself as 
curl -O -L https://github.com/F5Networks/neutron-lbaas/releases/download/v10.1.0/f5.tgz

That path does not exist.

## Requests
Provide details regarding what you would like to see added to our documentation:

### OpenStack project 

- [ X ] LBaaSv2
- [ ] Heat

### OpenStack version

- [ ] Liberty
- [ ] Mitaka
- [ X ] Newton

### Use Case 
Trying to install lbaas agent and driver

**Comment by thomsonjames** [comment]
Possibly as part of this, I found one here: https://github.com/F5Networks/f5-openstack-lbaasv2-driver/blob/master/f5.tgz

Used the curl command to get the file and untar:
curl -O -L https://github.com/F5Networks/f5-openstack-lbaasv2-driver/blob/master/f5.tgz
tar xvf f5.tgz -C /usr/lib/python2.7/site-packages/neutron_lbaas/drivers/

[root@newton neutron(keystone_admin)]# tar xvf ./f5.tgz -C /usr/lib/python2.7/site-packages/neutron_lbaas/drivers/

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

I'm not sure if this is a problem with f5.tgz file and I should file a bug there or if it's just documentation for the correct tar command.

**Comment by russokj** [comment]
I did not see a release v10.1.0, but there is a v.10.0.0 release, so use
curl -O -L https://github.com/F5Networks/neutron-lbaas/releases/download/v10.0.0/f5.tgz

If you want the latest, you would have to update the curl command you used to the following:
curl -o f5.tgz -L https://github.com/F5Networks/f5-openstack-lbaasv2-driver/blob/master/f5.tgz?raw=true

Looks like the documentation might need a little updating (or maybe it's ahead of the actual release).
