### ISSUE TITLE
bad links for sample files

### ISSUE THREAD

**Issue by thomsonjames** [F5Networks/f5-openstack-docs#241]
// Title: Provide a short but descriptive summary of the issue.
Sample ini file links incorrect

// **Do not include requests for development or report issues with code or products here.** 
https://github.com/F5Networks/f5-openstack-docs/blob/cd1b28c04e4e579d2c885f97cc4f879cc1e1f018/docs/lbaas/quick-reference.rst#id17

Set up the |agent|.

Sample configuration files:

Global Routed Mode example
GRE example [1]
VLAN example
VXLAN example [1]

These links are incorrect

## Bugs
Describe the bug in detail: 

- What doc are you reporting an issue with (provide URL)?

- What information is inaccurate? 

- Is information missing?

- Is a code sample incorrect?

## Requests
Provide details regarding what you would like to see added to our documentation:

### OpenStack project 

- [ ] LBaaSv2
- [ ] Heat

### OpenStack version

- [ ] Liberty
- [ ] Mitaka
- [ ] Newton

### Use Case 
(i.e., what are you trying to do that you can't find documentation for?)

**Comment by jputrino** [comment]
Hi @thomsonjames, thanks for the feedback. The links are formatted for use in our [docs website](http://clouddocs.f5.com/cloud/openstack/v1/lbaas/quick-reference.html), which unfortunately causes them to be broken here.

You can view the source files for these links in the f5-openstack-agent repo: https://github.com/F5Networks/f5-openstack-agent/tree/master/docs/_static/config_examples
